### ISSUE TITLE
Controller is not lazily started if only the effects field is accessed

### ISSUE THREAD

**Issue by FlowMo7** [floschu/control#26]
The Controller is not started lazily if only the `controller.effects` getter is called (and no other property such as the `controller.state` is accessed or `controller.dispatch` is being called).

There may be the `start()` logic missing here:
https://github.com/floschu/control/blob/7aa73304428729009a247cb292012ef1e994a69f/control-core/src/main/kotlin/at/florianschuster/control/implementation.kt#L130-L137

In a real world example, this would be relebant if e.g. in a transformer an `onStart()` with an `emitEffect()` should be called, which would then only be called after an action has been dispatched.

I'm just about to create a PR which adds a test for that as well as a possible fix, if the current behavior is not considered expected.

**Comment by floschu** [comment]
good catch 👍
