### ISSUE TITLE
Release 1.0.0

### ISSUE THREAD

**Issue by floschu** [floschu/control#8]
Starting with 1.0.0 add proper [release notes](https://help.github.com/en/github/administering-a-repository/managing-releases-in-a-repository).

- [x] ensure binary compatibility across releases (e.g. via https://github.com/Kotlin/binary-compatibility-validator)
- [x] add `CHANGELOG.md`
- [x] safeguard develop (PR's only)
- [ ] publish first official release with changelog

**Comment by FlowMo7** [comment]
I would also propose to use some tool to check binary compatibility on library version updates, such as i.e. https://github.com/Kotlin/binary-compatibility-validator, to see whether a breaking change in binary compatbility has occured.
